### ISSUE TITLE
Add CONTRIBUTING.md and GitHub Issue and PR templates

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/floating-ui-svelte#25]
We need a few additions to help contributors:

1. Add contribution information. Link it in the set repo `.md` file
2. Setup GitHub Issue templates (feature requests, docs, bug tickets, etc)
3. Setup GitHub PR templates (link, description, checklist)

**Comment by endigo9740** [comment]
Note: let's consider adding a `/docs/contributing` section to the website and link to this in `CONTRIBUTING.md`, so we have a single source of truth.
