### ISSUE TITLE
Add titles to all pages in the docs

### ISSUE THREAD

**Issue by jaakkonakaza** [skeletonlabs/floating-ui-svelte#65]
To improve accessibility and SEO

https://kit.svelte.dev/docs/accessibility#route-announcements

https://kit.svelte.dev/docs/seo#manual-setup

**Comment by endigo9740** [comment]
We'll likely save SEO for the late stage polish phase closer to launch. Part of SEO includes the social banners and such, so we'll want to ensure the design is finalized before we commit to all this.

**Comment by jaakkonakaza** [comment]
I think it would be nice to have page titles during development, for example if you have many tabs open, it's nice to quickly see which one is which

**Comment by endigo9740** [comment]
Yeah, we can break that off individually for now.
