### ISSUE TITLE
FloatingArrow does not align correctly on Firefox

### ISSUE THREAD

**Issue by JohnnyJTH** [skeletonlabs/floating-ui-svelte#74]
When hovering over the first tooltip example, the arrow does not position itself correctly:
![image](https://github.com/skeletonlabs/floating-ui-svelte/assets/64006750/ae50b326-bc31-401a-90bc-140361589ec5)

Link to page: https://floating-ui-svelte.vercel.app/tooltips
Firefox version: 126.0b9

**Comment by Hugos68** [comment]
I'm not sure if this has to do with the rendering of the arrow (FloatingArrow) or the position of the arrow (middlewareData.arrow) we should investigate this.

**Comment by endigo9740** [comment]
Good catch @JohnnyJTH, I'll look into this asap.

**Comment by Hugos68** [comment]
After doing some simple logging it appears to be a bug inside the FloatingArrow component. the `arrowX` and `arrowY` are identical on both browsers (Chrome left, Firefox right):
![image](https://github.com/skeletonlabs/floating-ui-svelte/assets/63101006/50edc779-a295-4ea6-98b9-335d171b94e9)
