### ISSUE TITLE
Extend CodeBlock component to support Shiki Decorators

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/floating-ui-svelte#96]
### Link to the Page

https://shiki.style/guide/decorations#decorations

### Describe the Issue (screenshots encouraged!)

Let's add a new prop to the `<CodeBlock>` to support decorators.

https://shiki.style/guide/decorations#decorations

Something like:

```html
<CodeBlock lang="ts" code={someCode} decorators={someDecorators} />
```

If we feel `decorators` is too long, we can shorten it to something like `mark`, ala Essential Code:

https://expressive-code.com/key-features/code-component/#mark--ins--del

**Comment by Hugos68** [comment]
This was closed per #95.
Not sure if I should have created a seperate PR instead, just letting you know @endigo9740.
Current API is:
```html
<CodeBlock lang="..." code="..." highlight="{1}" />
<!-- Or... -->
<CodeBlock lang="..." code="..." highlight="{[1,2,3]}" />
```
